services:
  # ------- backend -------
  backend:
    container_name: backend
    build:
      context: ../backend
    restart: always
    ports:
      - 3000:80
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: volopa
      DB_USERNAME: docker
      DB_PASSWORD: docker
    depends_on:
      - mysql

  # ------- mysql -------
  mysql:
    container_name: mysql
    image: mysql:8.0.30
    restart: always
    ports:
      - 3305:3306
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: volopa
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql

  # ------- frontend -------
  frontend:
    container_name: frontend
    build:
      context: ../frontend
    ports:
      - 8081:80
    restart: always
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8080/api/

  # ------- proxy -------
  proxy:
    container_name: proxy
    image: nginx:1.22-alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro